apiVersion: 1

datasources:
- name: mysql
  type: mysql
  access: proxy
  url: mysql:3306
  database: aquamon
  user: aquamon
  isDefault: true
  editable: true
  secureJsonData:
    password: password